name: {{name.lowerCase().snakeCase()}}
description: {{description}}

version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1
  puppeteer: ^2.12.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
