name: example
description: A sample command-line application to test {{name.lowerCase().snakeCase()}}
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  {{name.lowerCase().snakeCase()}}:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
