// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​h​i​s​ ​p​r​o​j​e​c​t​ ​w​a​s​ ​g​e​n​e​r​a​t​e​d​ ​w​i​t​h​ ​d​a​r​t​-​p​a​c​o​t​e​s​/​.​b​r​i​c​k​s​:​ ​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​d​a​r​t​-​p​a​c​o​t​e​s​/​.​b​r​i​c​k​s​/​t​r​e​e​/​m​a​s​t​e​r​/​a​p​l​i​c​a​c​a​o​-​w​e​b
	 */
	greetings: string
}

export type TranslationFunctions = {
	/**
	 * This project was generated with dart-pacotes/.bricks: https://github.com/dart-pacotes/.bricks/tree/master/aplicacao-web
	 */
	greetings: () => LocalizedString
}

export type Formatters = {}
